language: python
sudo: required
python:
  - "2.7"
  - "3.4"

install:
 - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ wily universe multiverse"
 - sudo apt-get update -qq
 - sudo apt-get install -y libsodium13
 - python setup.py install

script:
 - python -m unittest discover --start-directory test

notifications:
  email: false

after_success:
 - bash <(curl -s https://codecov.io/bash)
